version: '3'

services:
  api:
    container_name: go_api
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    tty:
      true
    volumes:
      - ./:/go/src/go/src/github.com/halkt/kaimemo-api

  mysql:
    container_name: mysql
    build: ./docker/mysql
    hostname: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./docker/mysql/env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "./mysql_data/mysql:/var/lib/mysql"
      - "./docker/mysql/my.conf:/etc/mysql/my.conf"
      - "./docker/mysql/init/:/docker-entrypoint-initdb.d"